version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECRR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 321469083854.dkr.ecr.us-east-1.amazonaws.com
      - echo Logged in to Amazon ECR successfully

  build:
    commands:
      - echo Building Docker Image for Flask Application
      - docker build -t flask_image .
      - echo Image built successfully

  post_build:
    commands:
      - echo Tagging Flask Docker image
      - docker tag flask_image:latest 321469083854.dkr.ecr.us-east-1.amazonaws.com/flask_image:latest
      - docker push 321469083854.dkr.ecr.us-east-1.amazonaws.com/flask_image:latest
      - echo Flask image pushed to ECR
      - printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
